language: objective-c

matrix:
  include:
    - osx_image: xcode8.1
    - osx_image: xcode8.2

script:
  - "xcodebuild -workspace Guanaco.xcworkspace -scheme Guanaco-iOS -sdk iphonesimulator -destination \"platform=iOS Simulator,name=iPhone 6\" test"
  - "xcodebuild -workspace Guanaco.xcworkspace -scheme Guanaco-OSX test"
