language: objective-c
osx_image: xcode8.3

xcode_workspace: Guanaco.xcworkspace

matrix:
  include:
    # iOS
    - xcode_scheme: Guanaco-iOS
      xcode_sdk: iphonesimulator
      before_script:
        - destination_id="platform=iOS Simulator,name=iPhone 6s"
        - echo "destination is $destination_id"
      env: 
        - JOB=IOS
    # macOS
    - xcode_scheme: Guanaco-OSX
      env: JOB=MACOS
    # macOS SPM
    - script:
        - swift --version
        - swift build
        - SWIFTPM_TEST=YES swift test
      git:
        submodules: false
      env: JOB=SWIFTPM_DARWIN
    # Linux SPM
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift --version
        - swift build
        - SWIFTPM_TEST=YES swift test
      git:
        submodules: false
      env: JOB=SWIFTPM_LINUX

script:
  - echo "xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME"${XCODE_SDK+ -sdk $XCODE_SDK}${destination_id+ -destination \"id=$destination_id\"} test"
  - $(!!)
